AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: NestJS on AWS Lambda

Resources:
  getDogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "dist/get-dogs.handler"
      Runtime: nodejs20.x
      CodeUri: ./dist
      MemorySize: 256
      Timeout: 20
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Petstore:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
  
    Metadata:
    BuildMethod: esbuild
    BuildProperties:
      Minify: true
      Target: es2020
      Sourcemap: true
      EntryPoints: 
        - get-dogs.ts

Outputs:
  HelloWorldApi:
    Description: 'API Gateway endpoint URL for the HelloWorld function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'